version: '3.8'

services:
    cassandra:
        image: cassandra:2.1
        container_name: l2sim-cassandra
        networks:
            public_net:
                ipv4_address: 192.168.61.2
        environment:
            CASSANDRA_CLUSTER_NAME: "OAI HSS Cluster"
            CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        healthcheck:
            test: /bin/bash -c "nodetool status"
            interval: 10s
            timeout: 5s
            retries: 5

    db_init:
        image: cassandra:2.1
        container_name: l2sim-db-init
        depends_on: [cassandra]
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 10
        networks:
            public_net:
                ipv4_address: 192.168.61.40
        volumes:
            - ./oai_db.cql:/home/oai_db.cql
        entrypoint: /bin/bash -c "cqlsh --file /home/oai_db.cql 192.168.61.2 && echo 'OK'"

    oai_hss:
        image: oai-hss:latest
        container_name: l2sim-oai-hss
        privileged: true
        depends_on: [cassandra]
        networks:
            public_net:
                ipv4_address: 192.168.61.3
        environment:
            REALM: openairinterface.org
            HSS_FQDN: hss.openairinterface.org
            PREFIX: /openair-hss/etc
            cassandra_Server_IP: 192.168.61.2
            OP_KEY: 1006220f3a478bf6b699f15c062e42b3
            LTE_K: 8baf473f2f8fd09487cccbd7097c6862
            APN1: oai.ipv4
            APN2: internet
            FIRST_IMSI: 208930100001110
            NB_USERS: 10
        healthcheck:
            test: /bin/bash -c "pgrep oai_hss"
            interval: 10s
            timeout: 5s
            retries: 5

    oai_mme:
        image: oai-mme:latest
        container_name: l2sim-oai-mme
        privileged: true
        depends_on: [oai_hss]
        networks:
            public_net:
                ipv4_address: 192.168.61.4
        environment:
            REALM: openairinterface.org
            PREFIX: /openair-mme/etc
            INSTANCE: 1
            PID_DIRECTORY: /var/run
            HSS_IP_ADDR: 192.168.61.3
            HSS_HOSTNAME: hss
            HSS_FQDN: hss.openairinterface.org
            HSS_REALM: openairinterface.org
            MCC: '208'
            MNC: '93'
            MME_GID: 32768
            MME_CODE: 3
            TAC_0: 1
            TAC_1: 2
            TAC_2: 3
            MME_FQDN: mme.openairinterface.org
            MME_S6A_IP_ADDR: 192.168.61.4
            MME_INTERFACE_NAME_FOR_S1_MME: eth0
            MME_IPV4_ADDRESS_FOR_S1_MME: 192.168.61.4
            MME_INTERFACE_NAME_FOR_S11: eth0
            MME_IPV4_ADDRESS_FOR_S11: 192.168.61.4
            MME_INTERFACE_NAME_FOR_S10: lo
            MME_IPV4_ADDRESS_FOR_S10: 127.0.0.10
            OUTPUT: CONSOLE
            SGW_IPV4_ADDRESS_FOR_S11_0: 192.168.61.5
            PEER_MME_IPV4_ADDRESS_FOR_S10_0: 0.0.0.0
            PEER_MME_IPV4_ADDRESS_FOR_S10_1: 0.0.0.0
            MCC_SGW_0: '208'
            MNC3_SGW_0: '093'
            TAC_LB_SGW_0: '01'
            TAC_HB_SGW_0: '00'
            MCC_MME_0: '208'
            MNC3_MME_0: '093'
            TAC_LB_MME_0: '02'
            TAC_HB_MME_0: '00'
            MCC_MME_1: '208'
            MNC3_MME_1: '093'
            TAC_LB_MME_1: '03'
            TAC_HB_MME_1: '00'
            TAC_LB_SGW_TEST_0: '03'
            TAC_HB_SGW_TEST_0: '00'
            SGW_IPV4_ADDRESS_FOR_S11_TEST_0: 0.0.0.0
        healthcheck:
            test: /bin/bash -c "pgrep oai_mme"
            interval: 10s
            timeout: 5s
            retries: 5

    oai_spgwc:
        image: oai-spgwc:latest
        privileged: true
        depends_on: [oai_mme]
        container_name: l2sim-oai-spgwc
        networks:
            public_net:
                ipv4_address: 192.168.61.5
        environment:
            TZ: Europe/Paris
            SGW_INTERFACE_NAME_FOR_S11: eth0
            PGW_INTERFACE_NAME_FOR_SX: eth0
            DEFAULT_DNS_IPV4_ADDRESS: 192.168.18.129
            DEFAULT_DNS_SEC_IPV4_ADDRESS: 8.8.4.4
            PUSH_PROTOCOL_OPTION: 'true'
            APN_NI_1: oai.ipv4
            APN_NI_2: oai2.ipv4
            DEFAULT_APN_NI_1: oai.ipv4
            UE_IP_ADDRESS_POOL_1: '12.1.1.2 - 12.1.1.254'
            UE_IP_ADDRESS_POOL_2: '12.0.0.2 - 12.0.0.254'
            MCC: '208'
            MNC: '93'
            MNC03: '093'
            TAC: 1
            GW_ID: 1
            REALM: openairinterface.org
        healthcheck:
            test: /bin/bash -c "pgrep oai_spgwc"
            interval: 10s
            timeout: 5s
            retries: 5

    oai_spgwu:
        image: oai-spgwu-tiny:latest
        privileged: true
        container_name: l2sim-oai-spgwu-tiny
        depends_on: [oai_spgwc]
        networks:
            public_net:
                ipv4_address: 192.168.61.6
        environment:
            TZ: Europe/Paris
            PID_DIRECTORY: /var/run
            INSTANCE: 1
            SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP: eth0
            PGW_INTERFACE_NAME_FOR_SGI: eth0
            SGW_INTERFACE_NAME_FOR_SX: eth0
            SPGWC0_IP_ADDRESS: 192.168.61.5
            NETWORK_UE_IP: '12.1.1.0/24'
            NETWORK_UE_NAT_OPTION: 'yes'
            MCC: '208'
            MNC: '93'
            MNC03: '093'
            TAC: 1
            GW_ID: 1
            REALM: openairinterface.org
        healthcheck:
            test: /bin/bash -c "pgrep oai_spgwu"
            interval: 10s
            timeout: 5s
            retries: 5

    trf_gen:
        image: trf-gen:production
        privileged: true
        container_name: l2sim-trf-gen
        networks:
            public_net:
                ipv4_address: 192.168.61.10
        entrypoint: /bin/bash -c "ip route add 12.1.1.0/24 via 192.168.61.6 dev eth0; sleep infinity"
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.61.6"
            interval: 10s
            timeout: 5s
            retries: 5

    enb_vnf_nfapi:
        image: oai-enb:develop
        privileged: true
        container_name: l2sim-enb-vnf
        environment:
            USE_FDD_FAPI_RCC: 'yes'
            ENB_NAME: vnf-in-docker
            MCC: '208'
            MNC: '93'
            MNC_LENGTH: 2
            TAC: 1
            UTRA_BAND_ID: 7
            DL_FREQUENCY_IN_MHZ: 2680
            UL_FREQUENCY_OFFSET_IN_MHZ: 120
            NID_CELL: 10
            NB_PRB: 25
            MME_S1C_IP_ADDRESS: 192.168.61.4
            F1_CU_IP_ADDRESS: 192.168.61.20
            S1C_IF_NAME: eth0
            S1U_IF_NAME: eth0
            F1_IF_NAME: eth0
            F1_DU_IP_ADDRESS: 192.168.61.25
        networks:
            public_net:
                ipv4_address: 192.168.61.20
        healthcheck:
            test: /bin/bash -c "pgrep lte-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    proxy_pnf_nfapi:
        image: oai-lte-multi-ue-proxy:latest
        privileged: true
        container_name: l2sim-proxy-pnf
        environment:
            NUM_UES: 1
            ENB_IP_ADDRESS: 192.168.61.20
            PROXY_IP_ADDRESS: 192.168.61.25
            UE_IP_ADDRESS: 192.168.61.30
        networks:
            public_net:
                ipv4_address: 192.168.61.25
        entrypoint: /bin/bash -c "/oai-lte-multi-ue-proxy/bin/proxy 1 192.168.61.20 192.168.61.25 192.168.61.30"
        healthcheck:
            test: /bin/bash -c "pgrep proxy"
            interval: 10s
            timeout: 5s
            retries: 5

    oai_ue_l2_sim0:
        image: oai-lte-ue:develop
        privileged: true
        container_name: l2sim-oai-ue0
        environment:
            USE_NFAPI: 'yes'
            UE_NFAPI_IF_NAME: eth0
            ENB_IP_ADDRESS: 192.168.61.25
            LTE_UE_IP_ADDRESS: 192.168.61.30
            MCC: '208'
            MNC: '93'
            SHORT_IMSI: '0100001111'
            LTE_KEY: '8baf473f2f8fd09487cccbd7097c6862'
            OPC: 'd52e6f6544c4c78b945dca2d3af26890'
            MSISDN: '33611123456'
            HPLMN: '20893'
            USE_ADDITIONAL_OPTIONS: --L2-emul 5 --num-ues 1 --nokrnmod 1 --node-number 2
        networks:
            public_net:
                ipv4_address: 192.168.61.30
        healthcheck:
            test: /bin/bash -c "pgrep lte-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: l2sim-net
        ipam:
            config:
                - subnet: 192.168.61.0/26
        driver_opts:
            com.docker.network.bridge.name: "l2sim-net"
